Rewritten, fixed a few glitches
jebeaudet/SunriseSunsetCalculator pull request #6
Opened 2018-10-24 10:02 UTC by yunruse

I made the algorithm precise to the second, and made the command-line output input zenith and output in a slightly more extractable format. I also rewritten the main calculation to become a lot smaller.

While it's now a tiny bit slower because it must re-do a few calculations, considering the only difference in the sunrise and sunset is in two lines, I'd say this algorithm is a wee bit easier on the eye.

2018-11-03 21:09 UTC, CarvellScott requested changes
I like the intention of simplifying the formula, it's a great idea! I didn't even think about `datetime.timetuple().tm_yday`. I also like that you eliminated a non-standard-library dependency. However, some inaccuracy has been introduced.

At the time of writing (2018-11-03), Google predicts sunset for my location (San Antonio, 29.4241° N, 98.4936° W) at about 18:46. With these changes, the script says sunset happens at 00:56:01. Even if that is UTC instead of local time, the minutes are quite a bit off. Unless of course Google's wrong here. If that's the case, might I ask where you got the value of "CIVIL_ZENITH" from?

Also, there's an AttributeError encountered when you use the -d parameter.

2018-11-03 21:09 UTC, CarvellScott commented on sunrise_sunset.py
> +    date = datetime.striptime(args.date, '%Y-%m-%d') if args.date else datetime.now()
This error is encountered when you use the "-d" argument:
`AttributeError: type object 'datetime.datetime' has no attribute 'striptime'`

2018-11-04 16:52 UTC, yunruse commented
Hi,

I believe you might have my commits confused for someone else's – if you check the diff, I didn't touch the ZENITH value, fix any imports, or use `.tm_yday`. The attribute error was easily fixed — a simple typo.

However, as far as I can tell after a few careful reads, there is no mathematical difference between the formula I used and the previous versions – only a change in precision. Debugging and printing values seems to show consistency, so as far as I can tell any errors are due to previous commits, apologies.

2018-11-04 17:31 UTC, CarvellScott commented
Odd. I could've swore I saw that in the diff somewhere. I must have messed up the comparison somehow. Sorry.

2022-12-14 22:25 UTC, closed without merging